package GUI;

import GUI.boss.*;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.io.*;
import java.net.Socket;
/**
 * @author Patryk Bocheński
 */
/**
 * The `BossGUI` class represents the main graphical user interface for the boss.
 * It extends `BaseGUI` and provides options for adding and managing workers.
 */
public class BossGUI extends BaseGUI implements ActionListener {
    /**
     * Button to open the Add Worker window.
     */
    JButton AddWorker;
    /**
     * Button to open the Manage Workers window.
     */
    JButton ManageWorker;
    /**
     * Button to return to the previous GUI (ClientGUI).
     */
    JButton goBackButton;
    /**
     * Instance of `AddWorkerWindow` to manage adding new workers.
     */
    private AddWorkerWindow addWorkerWindow = null;
    /**
     * Instance of `ManageWorkerWindow` to manage existing workers.
     */
    private ManageWorkerWindow manageWorkerWindow = null;

    /**
     * Constructs a new `BossGUI` window.
     *
     * @param title  The title to be displayed in the window's title bar.
     * @param socket The `Socket` object used for network communication with the server.
     * @throws IOException If an I/O error occurs when creating the `BossGUI`.
     */
    public BossGUI(String title, Socket socket) throws IOException {
        super(title, socket);
        init();
    }

    /**
     * Initializes the components and layout of the `BossGUI` window.
     * Sets up the main panel, title label, and buttons for managing workers.
     */
    @Override
    protected void init() {
        Container BossContainer = getContentPane();
        BossContainer.setLayout(new BorderLayout());
        setSize(400, 250);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setResizable(false);

        JLabel titleLabel = new JLabel("Boss Menu");
        titleLabel.setFont(new Font("Serif", Font.BOLD, 32));
        titleLabel.setForeground(Color.WHITE);
        titleLabel.setHorizontalAlignment(SwingConstants.CENTER);

        JPanel titlePanel = new JPanel(new BorderLayout());
        titlePanel.setBackground(Color.DARK_GRAY);
        titlePanel.setBorder(BorderFactory.createEmptyBorder(10, 0, 10, 0));
        titlePanel.add(titleLabel, BorderLayout.CENTER);

        AddWorker = new JButton("Add Worker");
        ManageWorker = new JButton("Manage Workers");
        goBackButton = new JButton("Go Back");

        Font buttonFont = new Font("Serif", Font.BOLD, 18);
        AddWorker.setFont(buttonFont);
        ManageWorker.setFont(buttonFont);
        goBackButton.setFont(buttonFont);

        JPanel buttonPanel = new JPanel(new GridLayout(3, 1, 10, 10));
        buttonPanel.setBorder(BorderFactory.createEmptyBorder(10, 35, 10, 35));
        buttonPanel.setBackground(Color.DARK_GRAY);
        buttonPanel.add(AddWorker);
        buttonPanel.add(ManageWorker);
        buttonPanel.add(goBackButton);
        AddWorker.addActionListener(this);
        ManageWorker.addActionListener(this);
        goBackButton.addActionListener(this);

        BossContainer.add(titlePanel, BorderLayout.NORTH);
        BossContainer.add(buttonPanel, BorderLayout.CENTER);
        styleButton(AddWorker);
        styleButton(ManageWorker);
        styleButton(goBackButton);
        style(titleLabel, labelFont, labelColor, labelBg);

        setVisible(true);
    }

    /**
     * Handles action events generated by buttons in the window.
     *
     * @param e The `ActionEvent` object.
     */
    @Override
    public void actionPerformed(ActionEvent e) {
        Object source = e.getSource();
        if (source == AddWorker) {
            try {
                objectOut.writeObject("TRY_OPEN_ADD_WORKER");
                objectOut.flush();
                boolean canOpen = objectIn.readBoolean();

                if (canOpen) {
                    addWorkerWindow = new AddWorkerWindow(BossGUI.this,this, objectOut);
                } else {
                    JOptionPane.showMessageDialog(this, "Windows is already open! Please wait!");
                }
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }

        } else if (source == ManageWorker) {
            try {
                objectOut.writeObject("TRY_OPEN_MANAGE_WORKER");
                objectOut.flush();
                boolean canOpen = objectIn.readBoolean();

                if (canOpen) {
                    manageWorkerWindow = new ManageWorkerWindow(BossGUI.this,this, objectOut, objectIn);
                } else {
                    JOptionPane.showMessageDialog(this, "Windows is already open! Please wait!");
                }
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }

        } else if (source == goBackButton) {
            dispose();
            try {
                socket = new Socket(serverIP,serverPort);
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
            new ClientGUI("Restaurant Management Application",socket);
        }
    }
}